package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Banks.
 */
public class Banks implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String BankCode;
    private String BankDescription;
    private String BankAltDescription;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public Banks() {
    }

    public Banks(Long id) {
        this.id = id;
    }

    public Banks(Long id, String BankCode, String BankDescription, String BankAltDescription, java.util.Date StampDate) {
        this.id = id;
        this.BankCode = BankCode;
        this.BankDescription = BankDescription;
        this.BankAltDescription = BankAltDescription;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getBankCode() {
        return BankCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBankCode(String BankCode) {
        this.BankCode = BankCode;
    }

    public String getBankDescription() {
        return BankDescription;
    }

    public void setBankDescription(String BankDescription) {
        this.BankDescription = BankDescription;
    }

    public String getBankAltDescription() {
        return BankAltDescription;
    }

    public void setBankAltDescription(String BankAltDescription) {
        this.BankAltDescription = BankAltDescription;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
