package me.SyncWise.Android.Database;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;

import me.SyncWise.Android.Database.BlankVisitContacts;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table BlankVisitContacts.
*/
public class BlankVisitContactsDao extends AbstractDao<BlankVisitContacts, Long> {

    public static final String TABLENAME = "BlankVisitContacts";

    /**
     * Properties of entity BlankVisitContacts.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property VisitID = new Property(1, long.class, "VisitID", false, "VisitID");
        public final static Property ClientContactID = new Property(2, int.class, "ClientContactID", false, "ClientContactID");
        public final static Property UserCode = new Property(3, String.class, "UserCode", false, "UserCode");
        public final static Property IsProcessed = new Property(4, int.class, "IsProcessed", false, "IsProcessed");
        public final static Property StampDate = new Property(5, java.util.Date.class, "StampDate", false, "StampDate");
    };


    public BlankVisitContactsDao(DaoConfig config) {
        super(config);
    }
    
    public BlankVisitContactsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'BlankVisitContacts' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'VisitID' INTEGER NOT NULL ," + // 1: VisitID
                "'ClientContactID' INTEGER NOT NULL ," + // 2: ClientContactID
                "'UserCode' TEXT NOT NULL ," + // 3: UserCode
                "'IsProcessed' INTEGER NOT NULL ," + // 4: IsProcessed
                "'StampDate' INTEGER NOT NULL );"); // 5: StampDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'BlankVisitContacts'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, BlankVisitContacts entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getVisitID());
        stmt.bindLong(3, entity.getClientContactID());
        stmt.bindString(4, entity.getUserCode());
        stmt.bindLong(5, entity.getIsProcessed());
        stmt.bindLong(6, entity.getStampDate().getTime());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public BlankVisitContacts readEntity(Cursor cursor, int offset) {
        BlankVisitContacts entity = new BlankVisitContacts( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // VisitID
            cursor.getInt(offset + 2), // ClientContactID
            cursor.getString(offset + 3), // UserCode
            cursor.getInt(offset + 4), // IsProcessed
            new java.util.Date(cursor.getLong(offset + 5)) // StampDate
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, BlankVisitContacts entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setVisitID(cursor.getLong(offset + 1));
        entity.setClientContactID(cursor.getInt(offset + 2));
        entity.setUserCode(cursor.getString(offset + 3));
        entity.setIsProcessed(cursor.getInt(offset + 4));
        entity.setStampDate(new java.util.Date(cursor.getLong(offset + 5)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(BlankVisitContacts entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(BlankVisitContacts entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
