package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Brands.
 */
public class Brands implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String BrandCode;
    /** Not-null value. */
    private String CompanyCode;
    private String BrandDescription;
    private String BrandAltDescription;
    private Double DivisionCode;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public Brands() {
    }

    public Brands(Long id) {
        this.id = id;
    }

    public Brands(Long id, String BrandCode, String CompanyCode, String BrandDescription, String BrandAltDescription, Double DivisionCode, java.util.Date StampDate) {
        this.id = id;
        this.BrandCode = BrandCode;
        this.CompanyCode = CompanyCode;
        this.BrandDescription = BrandDescription;
        this.BrandAltDescription = BrandAltDescription;
        this.DivisionCode = DivisionCode;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getBrandCode() {
        return BrandCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBrandCode(String BrandCode) {
        this.BrandCode = BrandCode;
    }

    /** Not-null value. */
    public String getCompanyCode() {
        return CompanyCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCompanyCode(String CompanyCode) {
        this.CompanyCode = CompanyCode;
    }

    public String getBrandDescription() {
        return BrandDescription;
    }

    public void setBrandDescription(String BrandDescription) {
        this.BrandDescription = BrandDescription;
    }

    public String getBrandAltDescription() {
        return BrandAltDescription;
    }

    public void setBrandAltDescription(String BrandAltDescription) {
        this.BrandAltDescription = BrandAltDescription;
    }

    public Double getDivisionCode() {
        return DivisionCode;
    }

    public void setDivisionCode(Double DivisionCode) {
        this.DivisionCode = DivisionCode;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
