package me.SyncWise.Android.Database;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;

import me.SyncWise.Android.Database.ClientDocumentImages;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ClientDocumentImages.
*/
public class ClientDocumentImagesDao extends AbstractDao<ClientDocumentImages, Long> {

    public static final String TABLENAME = "ClientDocumentImages";

    /**
     * Properties of entity ClientDocumentImages.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SubjectCode = new Property(1, String.class, "SubjectCode", false, "SubjectCode");
        public final static Property CompanyCode = new Property(2, String.class, "CompanyCode", false, "CompanyCode");
        public final static Property LineID = new Property(3, int.class, "LineID", false, "LineID");
        public final static Property VisitID = new Property(4, long.class, "VisitID", false, "VisitID");
        public final static Property ImageType = new Property(5, Integer.class, "ImageType", false, "ImageType");
        public final static Property Longitude = new Property(6, String.class, "Longitude", false, "Longitude");
        public final static Property Latitude = new Property(7, String.class, "Latitude", false, "Latitude");
        public final static Property IsProcessed = new Property(8, int.class, "IsProcessed", false, "IsProcessed");
        public final static Property StampDate = new Property(9, java.util.Date.class, "StampDate", false, "StampDate");
    };


    public ClientDocumentImagesDao(DaoConfig config) {
        super(config);
    }
    
    public ClientDocumentImagesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ClientDocumentImages' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'SubjectCode' TEXT NOT NULL ," + // 1: SubjectCode
                "'CompanyCode' TEXT NOT NULL ," + // 2: CompanyCode
                "'LineID' INTEGER NOT NULL ," + // 3: LineID
                "'VisitID' INTEGER NOT NULL ," + // 4: VisitID
                "'ImageType' INTEGER," + // 5: ImageType
                "'Longitude' TEXT," + // 6: Longitude
                "'Latitude' TEXT," + // 7: Latitude
                "'IsProcessed' INTEGER NOT NULL ," + // 8: IsProcessed
                "'StampDate' INTEGER NOT NULL );"); // 9: StampDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ClientDocumentImages'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ClientDocumentImages entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getSubjectCode());
        stmt.bindString(3, entity.getCompanyCode());
        stmt.bindLong(4, entity.getLineID());
        stmt.bindLong(5, entity.getVisitID());
 
        Integer ImageType = entity.getImageType();
        if (ImageType != null) {
            stmt.bindLong(6, ImageType);
        }
 
        String Longitude = entity.getLongitude();
        if (Longitude != null) {
            stmt.bindString(7, Longitude);
        }
 
        String Latitude = entity.getLatitude();
        if (Latitude != null) {
            stmt.bindString(8, Latitude);
        }
        stmt.bindLong(9, entity.getIsProcessed());
        stmt.bindLong(10, entity.getStampDate().getTime());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ClientDocumentImages readEntity(Cursor cursor, int offset) {
        ClientDocumentImages entity = new ClientDocumentImages( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // SubjectCode
            cursor.getString(offset + 2), // CompanyCode
            cursor.getInt(offset + 3), // LineID
            cursor.getLong(offset + 4), // VisitID
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // ImageType
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // Longitude
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // Latitude
            cursor.getInt(offset + 8), // IsProcessed
            new java.util.Date(cursor.getLong(offset + 9)) // StampDate
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ClientDocumentImages entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSubjectCode(cursor.getString(offset + 1));
        entity.setCompanyCode(cursor.getString(offset + 2));
        entity.setLineID(cursor.getInt(offset + 3));
        entity.setVisitID(cursor.getLong(offset + 4));
        entity.setImageType(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setLongitude(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setLatitude(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setIsProcessed(cursor.getInt(offset + 8));
        entity.setStampDate(new java.util.Date(cursor.getLong(offset + 9)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ClientDocumentImages entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ClientDocumentImages entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
