package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ClientAssetsPictures.
 */
public class ClientAssetsPictures implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String TransactionCode;
    private int LineID;
    private String ItemCode;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public ClientAssetsPictures() {
    }

    public ClientAssetsPictures(Long id) {
        this.id = id;
    }

    public ClientAssetsPictures(Long id, String TransactionCode, int LineID, String ItemCode, java.util.Date StampDate) {
        this.id = id;
        this.TransactionCode = TransactionCode;
        this.LineID = LineID;
        this.ItemCode = ItemCode;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTransactionCode() {
        return TransactionCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTransactionCode(String TransactionCode) {
        this.TransactionCode = TransactionCode;
    }

    public int getLineID() {
        return LineID;
    }

    public void setLineID(int LineID) {
        this.LineID = LineID;
    }

    public String getItemCode() {
        return ItemCode;
    }

    public void setItemCode(String ItemCode) {
        this.ItemCode = ItemCode;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
