package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ClientProperties.
 */
public class ClientProperties implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String ClientCode;
    /** Not-null value. */
    private String ClientPropertyValueCode;
    /** Not-null value. */
    private String CompanyCode;
    /** Not-null value. */
    private String DivisionCode;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public ClientProperties() {
    }

    public ClientProperties(Long id) {
        this.id = id;
    }

    public ClientProperties(Long id, String ClientCode, String ClientPropertyValueCode, String CompanyCode, String DivisionCode, java.util.Date StampDate) {
        this.id = id;
        this.ClientCode = ClientCode;
        this.ClientPropertyValueCode = ClientPropertyValueCode;
        this.CompanyCode = CompanyCode;
        this.DivisionCode = DivisionCode;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getClientCode() {
        return ClientCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setClientCode(String ClientCode) {
        this.ClientCode = ClientCode;
    }

    /** Not-null value. */
    public String getClientPropertyValueCode() {
        return ClientPropertyValueCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setClientPropertyValueCode(String ClientPropertyValueCode) {
        this.ClientPropertyValueCode = ClientPropertyValueCode;
    }

    /** Not-null value. */
    public String getCompanyCode() {
        return CompanyCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCompanyCode(String CompanyCode) {
        this.CompanyCode = CompanyCode;
    }

    /** Not-null value. */
    public String getDivisionCode() {
        return DivisionCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDivisionCode(String DivisionCode) {
        this.DivisionCode = DivisionCode;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
