package me.SyncWise.Android.Database;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;

import me.SyncWise.Android.Database.ClientAvailabilities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ClientAvailabilities.
*/
public class ClientAvailabilitiesDao extends AbstractDao<ClientAvailabilities, Long> {

    public static final String TABLENAME = "ClientAvailabilities";

    /**
     * Properties of entity ClientAvailabilities.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserCode = new Property(1, String.class, "UserCode", false, "UserCode");
        public final static Property ClientCode = new Property(2, String.class, "ClientCode", false, "ClientCode");
        public final static Property DivisionCode = new Property(3, String.class, "DivisionCode", false, "DivisionCode");
        public final static Property CompanyCode = new Property(4, String.class, "CompanyCode", false, "CompanyCode");
        public final static Property Day = new Property(5, String.class, "Day", false, "Day");
        public final static Property AvailabilityID = new Property(6, long.class, "AvailabilityID", false, "AvailabilityID");
        public final static Property StartTime = new Property(7, java.util.Date.class, "StartTime", false, "StartTime");
        public final static Property EndTime = new Property(8, java.util.Date.class, "EndTime", false, "EndTime");
        public final static Property AvailabilityStatus = new Property(9, Integer.class, "AvailabilityStatus", false, "AvailabilityStatus");
        public final static Property IsProcessed = new Property(10, int.class, "IsProcessed", false, "IsProcessed");
        public final static Property StampDate = new Property(11, java.util.Date.class, "StampDate", false, "StampDate");
    };


    public ClientAvailabilitiesDao(DaoConfig config) {
        super(config);
    }
    
    public ClientAvailabilitiesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ClientAvailabilities' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'UserCode' TEXT NOT NULL ," + // 1: UserCode
                "'ClientCode' TEXT NOT NULL ," + // 2: ClientCode
                "'DivisionCode' TEXT NOT NULL ," + // 3: DivisionCode
                "'CompanyCode' TEXT NOT NULL ," + // 4: CompanyCode
                "'Day' TEXT NOT NULL ," + // 5: Day
                "'AvailabilityID' INTEGER NOT NULL ," + // 6: AvailabilityID
                "'StartTime' INTEGER," + // 7: StartTime
                "'EndTime' INTEGER," + // 8: EndTime
                "'AvailabilityStatus' INTEGER," + // 9: AvailabilityStatus
                "'IsProcessed' INTEGER NOT NULL ," + // 10: IsProcessed
                "'StampDate' INTEGER NOT NULL );"); // 11: StampDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ClientAvailabilities'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ClientAvailabilities entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getUserCode());
        stmt.bindString(3, entity.getClientCode());
        stmt.bindString(4, entity.getDivisionCode());
        stmt.bindString(5, entity.getCompanyCode());
        stmt.bindString(6, entity.getDay());
        stmt.bindLong(7, entity.getAvailabilityID());
 
        java.util.Date StartTime = entity.getStartTime();
        if (StartTime != null) {
            stmt.bindLong(8, StartTime.getTime());
        }
 
        java.util.Date EndTime = entity.getEndTime();
        if (EndTime != null) {
            stmt.bindLong(9, EndTime.getTime());
        }
 
        Integer AvailabilityStatus = entity.getAvailabilityStatus();
        if (AvailabilityStatus != null) {
            stmt.bindLong(10, AvailabilityStatus);
        }
        stmt.bindLong(11, entity.getIsProcessed());
        stmt.bindLong(12, entity.getStampDate().getTime());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ClientAvailabilities readEntity(Cursor cursor, int offset) {
        ClientAvailabilities entity = new ClientAvailabilities( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // UserCode
            cursor.getString(offset + 2), // ClientCode
            cursor.getString(offset + 3), // DivisionCode
            cursor.getString(offset + 4), // CompanyCode
            cursor.getString(offset + 5), // Day
            cursor.getLong(offset + 6), // AvailabilityID
            cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)), // StartTime
            cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)), // EndTime
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // AvailabilityStatus
            cursor.getInt(offset + 10), // IsProcessed
            new java.util.Date(cursor.getLong(offset + 11)) // StampDate
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ClientAvailabilities entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserCode(cursor.getString(offset + 1));
        entity.setClientCode(cursor.getString(offset + 2));
        entity.setDivisionCode(cursor.getString(offset + 3));
        entity.setCompanyCode(cursor.getString(offset + 4));
        entity.setDay(cursor.getString(offset + 5));
        entity.setAvailabilityID(cursor.getLong(offset + 6));
        entity.setStartTime(cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)));
        entity.setEndTime(cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)));
        entity.setAvailabilityStatus(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setIsProcessed(cursor.getInt(offset + 10));
        entity.setStampDate(new java.util.Date(cursor.getLong(offset + 11)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ClientAvailabilities entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ClientAvailabilities entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
