package me.SyncWise.Android.Database;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;

import me.SyncWise.Android.Database.ClientItemClassificationLevels;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ClientItemClassificationLevels.
*/
public class ClientItemClassificationLevelsDao extends AbstractDao<ClientItemClassificationLevels, Long> {

    public static final String TABLENAME = "ClientItemClassificationLevels";

    /**
     * Properties of entity ClientItemClassificationLevels.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ClassificationLevelCode = new Property(1, String.class, "ClassificationLevelCode", false, "ClassificationLevelCode");
        public final static Property ClassificationLevelDescription = new Property(2, String.class, "ClassificationLevelDescription", false, "ClassificationLevelDescription");
        public final static Property ClassificationLevelAltDescription = new Property(3, String.class, "ClassificationLevelAltDescription", false, "ClassificationLevelAltDescription");
        public final static Property StampDate = new Property(4, java.util.Date.class, "StampDate", false, "StampDate");
    };


    public ClientItemClassificationLevelsDao(DaoConfig config) {
        super(config);
    }
    
    public ClientItemClassificationLevelsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ClientItemClassificationLevels' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ClassificationLevelCode' TEXT NOT NULL UNIQUE ," + // 1: ClassificationLevelCode
                "'ClassificationLevelDescription' TEXT," + // 2: ClassificationLevelDescription
                "'ClassificationLevelAltDescription' TEXT," + // 3: ClassificationLevelAltDescription
                "'StampDate' INTEGER NOT NULL );"); // 4: StampDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ClientItemClassificationLevels'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ClientItemClassificationLevels entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getClassificationLevelCode());
 
        String ClassificationLevelDescription = entity.getClassificationLevelDescription();
        if (ClassificationLevelDescription != null) {
            stmt.bindString(3, ClassificationLevelDescription);
        }
 
        String ClassificationLevelAltDescription = entity.getClassificationLevelAltDescription();
        if (ClassificationLevelAltDescription != null) {
            stmt.bindString(4, ClassificationLevelAltDescription);
        }
        stmt.bindLong(5, entity.getStampDate().getTime());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ClientItemClassificationLevels readEntity(Cursor cursor, int offset) {
        ClientItemClassificationLevels entity = new ClientItemClassificationLevels( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // ClassificationLevelCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // ClassificationLevelDescription
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // ClassificationLevelAltDescription
            new java.util.Date(cursor.getLong(offset + 4)) // StampDate
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ClientItemClassificationLevels entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setClassificationLevelCode(cursor.getString(offset + 1));
        entity.setClassificationLevelDescription(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setClassificationLevelAltDescription(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setStampDate(new java.util.Date(cursor.getLong(offset + 4)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ClientItemClassificationLevels entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ClientItemClassificationLevels entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
