package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ClientCreditings.
 */
public class ClientCreditings implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String CreditCode;
    /** Not-null value. */
    private String ClientCode;
    /** Not-null value. */
    private String CurrencyCode;
    /** Not-null value. */
    private String DivisionCode;
    /** Not-null value. */
    private String CompanyCode;
    private Double CreditAmount;
    private Double CreditBalance;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public ClientCreditings() {
    }

    public ClientCreditings(Long id) {
        this.id = id;
    }

    public ClientCreditings(Long id, String CreditCode, String ClientCode, String CurrencyCode, String DivisionCode, String CompanyCode, Double CreditAmount, Double CreditBalance, java.util.Date StampDate) {
        this.id = id;
        this.CreditCode = CreditCode;
        this.ClientCode = ClientCode;
        this.CurrencyCode = CurrencyCode;
        this.DivisionCode = DivisionCode;
        this.CompanyCode = CompanyCode;
        this.CreditAmount = CreditAmount;
        this.CreditBalance = CreditBalance;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCreditCode() {
        return CreditCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreditCode(String CreditCode) {
        this.CreditCode = CreditCode;
    }

    /** Not-null value. */
    public String getClientCode() {
        return ClientCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setClientCode(String ClientCode) {
        this.ClientCode = ClientCode;
    }

    /** Not-null value. */
    public String getCurrencyCode() {
        return CurrencyCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCurrencyCode(String CurrencyCode) {
        this.CurrencyCode = CurrencyCode;
    }

    /** Not-null value. */
    public String getDivisionCode() {
        return DivisionCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDivisionCode(String DivisionCode) {
        this.DivisionCode = DivisionCode;
    }

    /** Not-null value. */
    public String getCompanyCode() {
        return CompanyCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCompanyCode(String CompanyCode) {
        this.CompanyCode = CompanyCode;
    }

    public Double getCreditAmount() {
        return CreditAmount;
    }

    public void setCreditAmount(Double CreditAmount) {
        this.CreditAmount = CreditAmount;
    }

    public Double getCreditBalance() {
        return CreditBalance;
    }

    public void setCreditBalance(Double CreditBalance) {
        this.CreditBalance = CreditBalance;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
