package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ClientUserCollection.
 */
public class ClientUserCollection implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String UserCode;
    /** Not-null value. */
    private String CompanyCode;
    /** Not-null value. */
    private String ClientCode;
    /** Not-null value. */
    private String ClientCompanyCode;
    /** Not-null value. */
    private String DivisionCode;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public ClientUserCollection() {
    }

    public ClientUserCollection(Long id) {
        this.id = id;
    }

    public ClientUserCollection(Long id, String UserCode, String CompanyCode, String ClientCode, String ClientCompanyCode, String DivisionCode, java.util.Date StampDate) {
        this.id = id;
        this.UserCode = UserCode;
        this.CompanyCode = CompanyCode;
        this.ClientCode = ClientCode;
        this.ClientCompanyCode = ClientCompanyCode;
        this.DivisionCode = DivisionCode;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUserCode() {
        return UserCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserCode(String UserCode) {
        this.UserCode = UserCode;
    }

    /** Not-null value. */
    public String getCompanyCode() {
        return CompanyCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCompanyCode(String CompanyCode) {
        this.CompanyCode = CompanyCode;
    }

    /** Not-null value. */
    public String getClientCode() {
        return ClientCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setClientCode(String ClientCode) {
        this.ClientCode = ClientCode;
    }

    /** Not-null value. */
    public String getClientCompanyCode() {
        return ClientCompanyCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setClientCompanyCode(String ClientCompanyCode) {
        this.ClientCompanyCode = ClientCompanyCode;
    }

    /** Not-null value. */
    public String getDivisionCode() {
        return DivisionCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDivisionCode(String DivisionCode) {
        this.DivisionCode = DivisionCode;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
