package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CollectionImages.
 */
public class CollectionImages implements java.io.Serializable {

    private Long id;
    private int LineID;
    /** Not-null value. */
    private String CollectionCode;
    private String MoneyCategoryCode;
    private Integer Value;
    private String MoneyImageName;
    private int ImageStatus;
    private int IsProcessed;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public CollectionImages() {
    }

    public CollectionImages(Long id) {
        this.id = id;
    }

    public CollectionImages(Long id, int LineID, String CollectionCode, String MoneyCategoryCode, Integer Value, String MoneyImageName, int ImageStatus, int IsProcessed, java.util.Date StampDate) {
        this.id = id;
        this.LineID = LineID;
        this.CollectionCode = CollectionCode;
        this.MoneyCategoryCode = MoneyCategoryCode;
        this.Value = Value;
        this.MoneyImageName = MoneyImageName;
        this.ImageStatus = ImageStatus;
        this.IsProcessed = IsProcessed;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getLineID() {
        return LineID;
    }

    public void setLineID(int LineID) {
        this.LineID = LineID;
    }

    /** Not-null value. */
    public String getCollectionCode() {
        return CollectionCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCollectionCode(String CollectionCode) {
        this.CollectionCode = CollectionCode;
    }

    public String getMoneyCategoryCode() {
        return MoneyCategoryCode;
    }

    public void setMoneyCategoryCode(String MoneyCategoryCode) {
        this.MoneyCategoryCode = MoneyCategoryCode;
    }

    public Integer getValue() {
        return Value;
    }

    public void setValue(Integer Value) {
        this.Value = Value;
    }

    public String getMoneyImageName() {
        return MoneyImageName;
    }

    public void setMoneyImageName(String MoneyImageName) {
        this.MoneyImageName = MoneyImageName;
    }

    public int getImageStatus() {
        return ImageStatus;
    }

    public void setImageStatus(int ImageStatus) {
        this.ImageStatus = ImageStatus;
    }

    public int getIsProcessed() {
        return IsProcessed;
    }

    public void setIsProcessed(int IsProcessed) {
        this.IsProcessed = IsProcessed;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
