package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CollectionDetails.
 */
public class CollectionDetails implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String CollectionCode;
    private int LineID;
    private String DivisionCode;
    private Integer CollectionDetailType;
    private Double CollectionAmount;
    private String CurrencyCode;
    private Double CurrencyRate;
    private String CheckCode;
    private java.util.Date CheckDate;
    private String BankCode;
    private String BankDescription;
    private String BankBranchCode;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public CollectionDetails() {
    }

    public CollectionDetails(Long id) {
        this.id = id;
    }

    public CollectionDetails(Long id, String CollectionCode, int LineID, String DivisionCode, Integer CollectionDetailType, Double CollectionAmount, String CurrencyCode, Double CurrencyRate, String CheckCode, java.util.Date CheckDate, String BankCode, String BankDescription, String BankBranchCode, java.util.Date StampDate) {
        this.id = id;
        this.CollectionCode = CollectionCode;
        this.LineID = LineID;
        this.DivisionCode = DivisionCode;
        this.CollectionDetailType = CollectionDetailType;
        this.CollectionAmount = CollectionAmount;
        this.CurrencyCode = CurrencyCode;
        this.CurrencyRate = CurrencyRate;
        this.CheckCode = CheckCode;
        this.CheckDate = CheckDate;
        this.BankCode = BankCode;
        this.BankDescription = BankDescription;
        this.BankBranchCode = BankBranchCode;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCollectionCode() {
        return CollectionCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCollectionCode(String CollectionCode) {
        this.CollectionCode = CollectionCode;
    }

    public int getLineID() {
        return LineID;
    }

    public void setLineID(int LineID) {
        this.LineID = LineID;
    }

    public String getDivisionCode() {
        return DivisionCode;
    }

    public void setDivisionCode(String DivisionCode) {
        this.DivisionCode = DivisionCode;
    }

    public Integer getCollectionDetailType() {
        return CollectionDetailType;
    }

    public void setCollectionDetailType(Integer CollectionDetailType) {
        this.CollectionDetailType = CollectionDetailType;
    }

    public Double getCollectionAmount() {
        return CollectionAmount;
    }

    public void setCollectionAmount(Double CollectionAmount) {
        this.CollectionAmount = CollectionAmount;
    }

    public String getCurrencyCode() {
        return CurrencyCode;
    }

    public void setCurrencyCode(String CurrencyCode) {
        this.CurrencyCode = CurrencyCode;
    }

    public Double getCurrencyRate() {
        return CurrencyRate;
    }

    public void setCurrencyRate(Double CurrencyRate) {
        this.CurrencyRate = CurrencyRate;
    }

    public String getCheckCode() {
        return CheckCode;
    }

    public void setCheckCode(String CheckCode) {
        this.CheckCode = CheckCode;
    }

    public java.util.Date getCheckDate() {
        return CheckDate;
    }

    public void setCheckDate(java.util.Date CheckDate) {
        this.CheckDate = CheckDate;
    }

    public String getBankCode() {
        return BankCode;
    }

    public void setBankCode(String BankCode) {
        this.BankCode = BankCode;
    }

    public String getBankDescription() {
        return BankDescription;
    }

    public void setBankDescription(String BankDescription) {
        this.BankDescription = BankDescription;
    }

    public String getBankBranchCode() {
        return BankBranchCode;
    }

    public void setBankBranchCode(String BankBranchCode) {
        this.BankBranchCode = BankBranchCode;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
