package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Companies.
 */
public class Companies implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String CompanyCode;
    private String CompanyName;
    private String CompanyAltName;
    private String CompanyAddress;
    private String CompanyPhone;
    private String CompanyFax;
    private String CompanyVatNumber;
    private String StampNumber;
    private String POBox;
    private String CRNo;
    private String Email;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public Companies() {
    }

    public Companies(Long id) {
        this.id = id;
    }

    public Companies(Long id, String CompanyCode, String CompanyName, String CompanyAltName, String CompanyAddress, String CompanyPhone, String CompanyFax, String CompanyVatNumber, String StampNumber, String POBox, String CRNo, String Email, java.util.Date StampDate) {
        this.id = id;
        this.CompanyCode = CompanyCode;
        this.CompanyName = CompanyName;
        this.CompanyAltName = CompanyAltName;
        this.CompanyAddress = CompanyAddress;
        this.CompanyPhone = CompanyPhone;
        this.CompanyFax = CompanyFax;
        this.CompanyVatNumber = CompanyVatNumber;
        this.StampNumber = StampNumber;
        this.POBox = POBox;
        this.CRNo = CRNo;
        this.Email = Email;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCompanyCode() {
        return CompanyCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCompanyCode(String CompanyCode) {
        this.CompanyCode = CompanyCode;
    }

    public String getCompanyName() {
        return CompanyName;
    }

    public void setCompanyName(String CompanyName) {
        this.CompanyName = CompanyName;
    }

    public String getCompanyAltName() {
        return CompanyAltName;
    }

    public void setCompanyAltName(String CompanyAltName) {
        this.CompanyAltName = CompanyAltName;
    }

    public String getCompanyAddress() {
        return CompanyAddress;
    }

    public void setCompanyAddress(String CompanyAddress) {
        this.CompanyAddress = CompanyAddress;
    }

    public String getCompanyPhone() {
        return CompanyPhone;
    }

    public void setCompanyPhone(String CompanyPhone) {
        this.CompanyPhone = CompanyPhone;
    }

    public String getCompanyFax() {
        return CompanyFax;
    }

    public void setCompanyFax(String CompanyFax) {
        this.CompanyFax = CompanyFax;
    }

    public String getCompanyVatNumber() {
        return CompanyVatNumber;
    }

    public void setCompanyVatNumber(String CompanyVatNumber) {
        this.CompanyVatNumber = CompanyVatNumber;
    }

    public String getStampNumber() {
        return StampNumber;
    }

    public void setStampNumber(String StampNumber) {
        this.StampNumber = StampNumber;
    }

    public String getPOBox() {
        return POBox;
    }

    public void setPOBox(String POBox) {
        this.POBox = POBox;
    }

    public String getCRNo() {
        return CRNo;
    }

    public void setCRNo(String CRNo) {
        this.CRNo = CRNo;
    }

    public String getEmail() {
        return Email;
    }

    public void setEmail(String Email) {
        this.Email = Email;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
