package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Currencies.
 */
public class Currencies implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String CurrencyCode;
    private String CurrencyName;
    private String CurrencyAltName;
    private String CurrencySymbol;
    private Integer CurrencyRounding;
    private Integer CurrencyPriority;
    private Double CurrencyUpperMargin;
    private Double CurrencyLowerMargin;
    private Double CurrencyRate;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public Currencies() {
    }

    public Currencies(Long id) {
        this.id = id;
    }

    public Currencies(Long id, String CurrencyCode, String CurrencyName, String CurrencyAltName, String CurrencySymbol, Integer CurrencyRounding, Integer CurrencyPriority, Double CurrencyUpperMargin, Double CurrencyLowerMargin, Double CurrencyRate, java.util.Date StampDate) {
        this.id = id;
        this.CurrencyCode = CurrencyCode;
        this.CurrencyName = CurrencyName;
        this.CurrencyAltName = CurrencyAltName;
        this.CurrencySymbol = CurrencySymbol;
        this.CurrencyRounding = CurrencyRounding;
        this.CurrencyPriority = CurrencyPriority;
        this.CurrencyUpperMargin = CurrencyUpperMargin;
        this.CurrencyLowerMargin = CurrencyLowerMargin;
        this.CurrencyRate = CurrencyRate;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCurrencyCode() {
        return CurrencyCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCurrencyCode(String CurrencyCode) {
        this.CurrencyCode = CurrencyCode;
    }

    public String getCurrencyName() {
        return CurrencyName;
    }

    public void setCurrencyName(String CurrencyName) {
        this.CurrencyName = CurrencyName;
    }

    public String getCurrencyAltName() {
        return CurrencyAltName;
    }

    public void setCurrencyAltName(String CurrencyAltName) {
        this.CurrencyAltName = CurrencyAltName;
    }

    public String getCurrencySymbol() {
        return CurrencySymbol;
    }

    public void setCurrencySymbol(String CurrencySymbol) {
        this.CurrencySymbol = CurrencySymbol;
    }

    public Integer getCurrencyRounding() {
        return CurrencyRounding;
    }

    public void setCurrencyRounding(Integer CurrencyRounding) {
        this.CurrencyRounding = CurrencyRounding;
    }

    public Integer getCurrencyPriority() {
        return CurrencyPriority;
    }

    public void setCurrencyPriority(Integer CurrencyPriority) {
        this.CurrencyPriority = CurrencyPriority;
    }

    public Double getCurrencyUpperMargin() {
        return CurrencyUpperMargin;
    }

    public void setCurrencyUpperMargin(Double CurrencyUpperMargin) {
        this.CurrencyUpperMargin = CurrencyUpperMargin;
    }

    public Double getCurrencyLowerMargin() {
        return CurrencyLowerMargin;
    }

    public void setCurrencyLowerMargin(Double CurrencyLowerMargin) {
        this.CurrencyLowerMargin = CurrencyLowerMargin;
    }

    public Double getCurrencyRate() {
        return CurrencyRate;
    }

    public void setCurrencyRate(Double CurrencyRate) {
        this.CurrencyRate = CurrencyRate;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
