package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Divisions.
 */
public class Divisions implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String DivisionCode;
    private String DivisionName;
    private String DivisionAltName;
    /** Not-null value. */
    private String CompanyCode;
    private String ParentCode;
    private Integer ApplyExiceTax;
    private Integer ApplyFreeExiceTax;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public Divisions() {
    }

    public Divisions(Long id) {
        this.id = id;
    }

    public Divisions(Long id, String DivisionCode, String DivisionName, String DivisionAltName, String CompanyCode, String ParentCode, Integer ApplyExiceTax, Integer ApplyFreeExiceTax, java.util.Date StampDate) {
        this.id = id;
        this.DivisionCode = DivisionCode;
        this.DivisionName = DivisionName;
        this.DivisionAltName = DivisionAltName;
        this.CompanyCode = CompanyCode;
        this.ParentCode = ParentCode;
        this.ApplyExiceTax = ApplyExiceTax;
        this.ApplyFreeExiceTax = ApplyFreeExiceTax;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDivisionCode() {
        return DivisionCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDivisionCode(String DivisionCode) {
        this.DivisionCode = DivisionCode;
    }

    public String getDivisionName() {
        return DivisionName;
    }

    public void setDivisionName(String DivisionName) {
        this.DivisionName = DivisionName;
    }

    public String getDivisionAltName() {
        return DivisionAltName;
    }

    public void setDivisionAltName(String DivisionAltName) {
        this.DivisionAltName = DivisionAltName;
    }

    /** Not-null value. */
    public String getCompanyCode() {
        return CompanyCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCompanyCode(String CompanyCode) {
        this.CompanyCode = CompanyCode;
    }

    public String getParentCode() {
        return ParentCode;
    }

    public void setParentCode(String ParentCode) {
        this.ParentCode = ParentCode;
    }

    public Integer getApplyExiceTax() {
        return ApplyExiceTax;
    }

    public void setApplyExiceTax(Integer ApplyExiceTax) {
        this.ApplyExiceTax = ApplyExiceTax;
    }

    public Integer getApplyFreeExiceTax() {
        return ApplyFreeExiceTax;
    }

    public void setApplyFreeExiceTax(Integer ApplyFreeExiceTax) {
        this.ApplyFreeExiceTax = ApplyFreeExiceTax;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
