package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ForceSyncJourneys.
 */
public class ForceSyncJourneys implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String JourneyCode;
    private String UserCode;
    private Integer SyncStatus;
    private String PassCode;
    private int IsProcessed;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public ForceSyncJourneys() {
    }

    public ForceSyncJourneys(Long id) {
        this.id = id;
    }

    public ForceSyncJourneys(Long id, String JourneyCode, String UserCode, Integer SyncStatus, String PassCode, int IsProcessed, java.util.Date StampDate) {
        this.id = id;
        this.JourneyCode = JourneyCode;
        this.UserCode = UserCode;
        this.SyncStatus = SyncStatus;
        this.PassCode = PassCode;
        this.IsProcessed = IsProcessed;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getJourneyCode() {
        return JourneyCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setJourneyCode(String JourneyCode) {
        this.JourneyCode = JourneyCode;
    }

    public String getUserCode() {
        return UserCode;
    }

    public void setUserCode(String UserCode) {
        this.UserCode = UserCode;
    }

    public Integer getSyncStatus() {
        return SyncStatus;
    }

    public void setSyncStatus(Integer SyncStatus) {
        this.SyncStatus = SyncStatus;
    }

    public String getPassCode() {
        return PassCode;
    }

    public void setPassCode(String PassCode) {
        this.PassCode = PassCode;
    }

    public int getIsProcessed() {
        return IsProcessed;
    }

    public void setIsProcessed(int IsProcessed) {
        this.IsProcessed = IsProcessed;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
