package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ItemVolumes.
 */
public class ItemVolumes implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String ItemCode;
    /** Not-null value. */
    private String CompanyCode;
    private Double BigVolumeCM;
    private Double MediumVolumeCM;
    private Double SmallVolumeCM;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public ItemVolumes() {
    }

    public ItemVolumes(Long id) {
        this.id = id;
    }

    public ItemVolumes(Long id, String ItemCode, String CompanyCode, Double BigVolumeCM, Double MediumVolumeCM, Double SmallVolumeCM, java.util.Date StampDate) {
        this.id = id;
        this.ItemCode = ItemCode;
        this.CompanyCode = CompanyCode;
        this.BigVolumeCM = BigVolumeCM;
        this.MediumVolumeCM = MediumVolumeCM;
        this.SmallVolumeCM = SmallVolumeCM;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getItemCode() {
        return ItemCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setItemCode(String ItemCode) {
        this.ItemCode = ItemCode;
    }

    /** Not-null value. */
    public String getCompanyCode() {
        return CompanyCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCompanyCode(String CompanyCode) {
        this.CompanyCode = CompanyCode;
    }

    public Double getBigVolumeCM() {
        return BigVolumeCM;
    }

    public void setBigVolumeCM(Double BigVolumeCM) {
        this.BigVolumeCM = BigVolumeCM;
    }

    public Double getMediumVolumeCM() {
        return MediumVolumeCM;
    }

    public void setMediumVolumeCM(Double MediumVolumeCM) {
        this.MediumVolumeCM = MediumVolumeCM;
    }

    public Double getSmallVolumeCM() {
        return SmallVolumeCM;
    }

    public void setSmallVolumeCM(Double SmallVolumeCM) {
        this.SmallVolumeCM = SmallVolumeCM;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
