package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MsgHeader.
 */
public class MsgHeader implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String MsgCode;
    private String CompanyCode;
    private String SubjectCode;
    private String MsgTitle;
    private String MsgBody;
    private java.util.Date MsgDate;
    private java.util.Date StartDate;
    private java.util.Date EndDate;
    private String IsActive;
    private String MsgType;

	private static final long serialVersionUID = 1L;

    public MsgHeader() {
    }

    public MsgHeader(Long id) {
        this.id = id;
    }

    public MsgHeader(Long id, String MsgCode, String CompanyCode, String SubjectCode, String MsgTitle, String MsgBody, java.util.Date MsgDate, java.util.Date StartDate, java.util.Date EndDate, String IsActive, String MsgType) {
        this.id = id;
        this.MsgCode = MsgCode;
        this.CompanyCode = CompanyCode;
        this.SubjectCode = SubjectCode;
        this.MsgTitle = MsgTitle;
        this.MsgBody = MsgBody;
        this.MsgDate = MsgDate;
        this.StartDate = StartDate;
        this.EndDate = EndDate;
        this.IsActive = IsActive;
        this.MsgType = MsgType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getMsgCode() {
        return MsgCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMsgCode(String MsgCode) {
        this.MsgCode = MsgCode;
    }

    public String getCompanyCode() {
        return CompanyCode;
    }

    public void setCompanyCode(String CompanyCode) {
        this.CompanyCode = CompanyCode;
    }

    public String getSubjectCode() {
        return SubjectCode;
    }

    public void setSubjectCode(String SubjectCode) {
        this.SubjectCode = SubjectCode;
    }

    public String getMsgTitle() {
        return MsgTitle;
    }

    public void setMsgTitle(String MsgTitle) {
        this.MsgTitle = MsgTitle;
    }

    public String getMsgBody() {
        return MsgBody;
    }

    public void setMsgBody(String MsgBody) {
        this.MsgBody = MsgBody;
    }

    public java.util.Date getMsgDate() {
        return MsgDate;
    }

    public void setMsgDate(java.util.Date MsgDate) {
        this.MsgDate = MsgDate;
    }

    public java.util.Date getStartDate() {
        return StartDate;
    }

    public void setStartDate(java.util.Date StartDate) {
        this.StartDate = StartDate;
    }

    public java.util.Date getEndDate() {
        return EndDate;
    }

    public void setEndDate(java.util.Date EndDate) {
        this.EndDate = EndDate;
    }

    public String getIsActive() {
        return IsActive;
    }

    public void setIsActive(String IsActive) {
        this.IsActive = IsActive;
    }

    public String getMsgType() {
        return MsgType;
    }

    public void setMsgType(String MsgType) {
        this.MsgType = MsgType;
    }

}
