package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NewClients.
 */
public class NewClients implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String ClientCode;
    /** Not-null value. */
    private String CompanyCode;
    /** Not-null value. */
    private String DivisionCode;
    private String AccountNumber;
    private String UserCode;
    private String ClientName;
    private String ClientAltName;
    private String ClientPhone;
    private String Mobile;
    private String Fax;
    private String Email;
    private String FinacialNumber;
    private String CNSS;
    private String SyndicateNumber;
    private String LicenseNumber;
    private String ClientAddress;
    private String Latitude;
    private String Longitude;
    private int IsProcessed;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public NewClients() {
    }

    public NewClients(Long id) {
        this.id = id;
    }

    public NewClients(Long id, String ClientCode, String CompanyCode, String DivisionCode, String AccountNumber, String UserCode, String ClientName, String ClientAltName, String ClientPhone, String Mobile, String Fax, String Email, String FinacialNumber, String CNSS, String SyndicateNumber, String LicenseNumber, String ClientAddress, String Latitude, String Longitude, int IsProcessed, java.util.Date StampDate) {
        this.id = id;
        this.ClientCode = ClientCode;
        this.CompanyCode = CompanyCode;
        this.DivisionCode = DivisionCode;
        this.AccountNumber = AccountNumber;
        this.UserCode = UserCode;
        this.ClientName = ClientName;
        this.ClientAltName = ClientAltName;
        this.ClientPhone = ClientPhone;
        this.Mobile = Mobile;
        this.Fax = Fax;
        this.Email = Email;
        this.FinacialNumber = FinacialNumber;
        this.CNSS = CNSS;
        this.SyndicateNumber = SyndicateNumber;
        this.LicenseNumber = LicenseNumber;
        this.ClientAddress = ClientAddress;
        this.Latitude = Latitude;
        this.Longitude = Longitude;
        this.IsProcessed = IsProcessed;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getClientCode() {
        return ClientCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setClientCode(String ClientCode) {
        this.ClientCode = ClientCode;
    }

    /** Not-null value. */
    public String getCompanyCode() {
        return CompanyCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCompanyCode(String CompanyCode) {
        this.CompanyCode = CompanyCode;
    }

    /** Not-null value. */
    public String getDivisionCode() {
        return DivisionCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDivisionCode(String DivisionCode) {
        this.DivisionCode = DivisionCode;
    }

    public String getAccountNumber() {
        return AccountNumber;
    }

    public void setAccountNumber(String AccountNumber) {
        this.AccountNumber = AccountNumber;
    }

    public String getUserCode() {
        return UserCode;
    }

    public void setUserCode(String UserCode) {
        this.UserCode = UserCode;
    }

    public String getClientName() {
        return ClientName;
    }

    public void setClientName(String ClientName) {
        this.ClientName = ClientName;
    }

    public String getClientAltName() {
        return ClientAltName;
    }

    public void setClientAltName(String ClientAltName) {
        this.ClientAltName = ClientAltName;
    }

    public String getClientPhone() {
        return ClientPhone;
    }

    public void setClientPhone(String ClientPhone) {
        this.ClientPhone = ClientPhone;
    }

    public String getMobile() {
        return Mobile;
    }

    public void setMobile(String Mobile) {
        this.Mobile = Mobile;
    }

    public String getFax() {
        return Fax;
    }

    public void setFax(String Fax) {
        this.Fax = Fax;
    }

    public String getEmail() {
        return Email;
    }

    public void setEmail(String Email) {
        this.Email = Email;
    }

    public String getFinacialNumber() {
        return FinacialNumber;
    }

    public void setFinacialNumber(String FinacialNumber) {
        this.FinacialNumber = FinacialNumber;
    }

    public String getCNSS() {
        return CNSS;
    }

    public void setCNSS(String CNSS) {
        this.CNSS = CNSS;
    }

    public String getSyndicateNumber() {
        return SyndicateNumber;
    }

    public void setSyndicateNumber(String SyndicateNumber) {
        this.SyndicateNumber = SyndicateNumber;
    }

    public String getLicenseNumber() {
        return LicenseNumber;
    }

    public void setLicenseNumber(String LicenseNumber) {
        this.LicenseNumber = LicenseNumber;
    }

    public String getClientAddress() {
        return ClientAddress;
    }

    public void setClientAddress(String ClientAddress) {
        this.ClientAddress = ClientAddress;
    }

    public String getLatitude() {
        return Latitude;
    }

    public void setLatitude(String Latitude) {
        this.Latitude = Latitude;
    }

    public String getLongitude() {
        return Longitude;
    }

    public void setLongitude(String Longitude) {
        this.Longitude = Longitude;
    }

    public int getIsProcessed() {
        return IsProcessed;
    }

    public void setIsProcessed(int IsProcessed) {
        this.IsProcessed = IsProcessed;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
