package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ObjectiveAssignments.
 */
public class ObjectiveAssignments implements java.io.Serializable {

    private Long id;
    private Long ObjectiveID;
    private String AssignmentCode;
    private Integer AssignmentType;
    private String AssignmentSource;
    private String DivisionCode;
    private String CompanyCode;
    private int IsProcessed;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public ObjectiveAssignments() {
    }

    public ObjectiveAssignments(Long id) {
        this.id = id;
    }

    public ObjectiveAssignments(Long id, Long ObjectiveID, String AssignmentCode, Integer AssignmentType, String AssignmentSource, String DivisionCode, String CompanyCode, int IsProcessed, java.util.Date StampDate) {
        this.id = id;
        this.ObjectiveID = ObjectiveID;
        this.AssignmentCode = AssignmentCode;
        this.AssignmentType = AssignmentType;
        this.AssignmentSource = AssignmentSource;
        this.DivisionCode = DivisionCode;
        this.CompanyCode = CompanyCode;
        this.IsProcessed = IsProcessed;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getObjectiveID() {
        return ObjectiveID;
    }

    public void setObjectiveID(Long ObjectiveID) {
        this.ObjectiveID = ObjectiveID;
    }

    public String getAssignmentCode() {
        return AssignmentCode;
    }

    public void setAssignmentCode(String AssignmentCode) {
        this.AssignmentCode = AssignmentCode;
    }

    public Integer getAssignmentType() {
        return AssignmentType;
    }

    public void setAssignmentType(Integer AssignmentType) {
        this.AssignmentType = AssignmentType;
    }

    public String getAssignmentSource() {
        return AssignmentSource;
    }

    public void setAssignmentSource(String AssignmentSource) {
        this.AssignmentSource = AssignmentSource;
    }

    public String getDivisionCode() {
        return DivisionCode;
    }

    public void setDivisionCode(String DivisionCode) {
        this.DivisionCode = DivisionCode;
    }

    public String getCompanyCode() {
        return CompanyCode;
    }

    public void setCompanyCode(String CompanyCode) {
        this.CompanyCode = CompanyCode;
    }

    public int getIsProcessed() {
        return IsProcessed;
    }

    public void setIsProcessed(int IsProcessed) {
        this.IsProcessed = IsProcessed;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
