package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PromotionDetails.
 */
public class PromotionDetails implements java.io.Serializable {

    private Long id;
    private int PromotionID;
    private int LineID;
    private String OrderedItemCode;
    private Double OrderedQuantity;
    private Double BasicOrderedQuantity;
    private String OrderedUnit;
    private String OfferedItemCode;
    private Double OfferedQuantity;
    private Double BasicOfferedQuantity;
    private String OfferedUnit;
    private Integer OfferedLimit;
    private Double DiscountAmount;
    private Double TotalAmount;
    private Double DiscountPercentage;
    private Integer PromotionDetailType;
    private Integer ApplyOriginalDiscount;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public PromotionDetails() {
    }

    public PromotionDetails(Long id) {
        this.id = id;
    }

    public PromotionDetails(Long id, int PromotionID, int LineID, String OrderedItemCode, Double OrderedQuantity, Double BasicOrderedQuantity, String OrderedUnit, String OfferedItemCode, Double OfferedQuantity, Double BasicOfferedQuantity, String OfferedUnit, Integer OfferedLimit, Double DiscountAmount, Double TotalAmount, Double DiscountPercentage, Integer PromotionDetailType, Integer ApplyOriginalDiscount, java.util.Date StampDate) {
        this.id = id;
        this.PromotionID = PromotionID;
        this.LineID = LineID;
        this.OrderedItemCode = OrderedItemCode;
        this.OrderedQuantity = OrderedQuantity;
        this.BasicOrderedQuantity = BasicOrderedQuantity;
        this.OrderedUnit = OrderedUnit;
        this.OfferedItemCode = OfferedItemCode;
        this.OfferedQuantity = OfferedQuantity;
        this.BasicOfferedQuantity = BasicOfferedQuantity;
        this.OfferedUnit = OfferedUnit;
        this.OfferedLimit = OfferedLimit;
        this.DiscountAmount = DiscountAmount;
        this.TotalAmount = TotalAmount;
        this.DiscountPercentage = DiscountPercentage;
        this.PromotionDetailType = PromotionDetailType;
        this.ApplyOriginalDiscount = ApplyOriginalDiscount;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getPromotionID() {
        return PromotionID;
    }

    public void setPromotionID(int PromotionID) {
        this.PromotionID = PromotionID;
    }

    public int getLineID() {
        return LineID;
    }

    public void setLineID(int LineID) {
        this.LineID = LineID;
    }

    public String getOrderedItemCode() {
        return OrderedItemCode;
    }

    public void setOrderedItemCode(String OrderedItemCode) {
        this.OrderedItemCode = OrderedItemCode;
    }

    public Double getOrderedQuantity() {
        return OrderedQuantity;
    }

    public void setOrderedQuantity(Double OrderedQuantity) {
        this.OrderedQuantity = OrderedQuantity;
    }

    public Double getBasicOrderedQuantity() {
        return BasicOrderedQuantity;
    }

    public void setBasicOrderedQuantity(Double BasicOrderedQuantity) {
        this.BasicOrderedQuantity = BasicOrderedQuantity;
    }

    public String getOrderedUnit() {
        return OrderedUnit;
    }

    public void setOrderedUnit(String OrderedUnit) {
        this.OrderedUnit = OrderedUnit;
    }

    public String getOfferedItemCode() {
        return OfferedItemCode;
    }

    public void setOfferedItemCode(String OfferedItemCode) {
        this.OfferedItemCode = OfferedItemCode;
    }

    public Double getOfferedQuantity() {
        return OfferedQuantity;
    }

    public void setOfferedQuantity(Double OfferedQuantity) {
        this.OfferedQuantity = OfferedQuantity;
    }

    public Double getBasicOfferedQuantity() {
        return BasicOfferedQuantity;
    }

    public void setBasicOfferedQuantity(Double BasicOfferedQuantity) {
        this.BasicOfferedQuantity = BasicOfferedQuantity;
    }

    public String getOfferedUnit() {
        return OfferedUnit;
    }

    public void setOfferedUnit(String OfferedUnit) {
        this.OfferedUnit = OfferedUnit;
    }

    public Integer getOfferedLimit() {
        return OfferedLimit;
    }

    public void setOfferedLimit(Integer OfferedLimit) {
        this.OfferedLimit = OfferedLimit;
    }

    public Double getDiscountAmount() {
        return DiscountAmount;
    }

    public void setDiscountAmount(Double DiscountAmount) {
        this.DiscountAmount = DiscountAmount;
    }

    public Double getTotalAmount() {
        return TotalAmount;
    }

    public void setTotalAmount(Double TotalAmount) {
        this.TotalAmount = TotalAmount;
    }

    public Double getDiscountPercentage() {
        return DiscountPercentage;
    }

    public void setDiscountPercentage(Double DiscountPercentage) {
        this.DiscountPercentage = DiscountPercentage;
    }

    public Integer getPromotionDetailType() {
        return PromotionDetailType;
    }

    public void setPromotionDetailType(Integer PromotionDetailType) {
        this.PromotionDetailType = PromotionDetailType;
    }

    public Integer getApplyOriginalDiscount() {
        return ApplyOriginalDiscount;
    }

    public void setApplyOriginalDiscount(Integer ApplyOriginalDiscount) {
        this.ApplyOriginalDiscount = ApplyOriginalDiscount;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
