package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table QuestionAnswers.
 */
public class QuestionAnswers implements java.io.Serializable {

    private Long id;
    private int QuestionAnswerID;
    private int LineID;
    private String QuestionAnswerDescription;
    private String QuestionAnswerAltDescription;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public QuestionAnswers() {
    }

    public QuestionAnswers(Long id) {
        this.id = id;
    }

    public QuestionAnswers(Long id, int QuestionAnswerID, int LineID, String QuestionAnswerDescription, String QuestionAnswerAltDescription, java.util.Date StampDate) {
        this.id = id;
        this.QuestionAnswerID = QuestionAnswerID;
        this.LineID = LineID;
        this.QuestionAnswerDescription = QuestionAnswerDescription;
        this.QuestionAnswerAltDescription = QuestionAnswerAltDescription;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getQuestionAnswerID() {
        return QuestionAnswerID;
    }

    public void setQuestionAnswerID(int QuestionAnswerID) {
        this.QuestionAnswerID = QuestionAnswerID;
    }

    public int getLineID() {
        return LineID;
    }

    public void setLineID(int LineID) {
        this.LineID = LineID;
    }

    public String getQuestionAnswerDescription() {
        return QuestionAnswerDescription;
    }

    public void setQuestionAnswerDescription(String QuestionAnswerDescription) {
        this.QuestionAnswerDescription = QuestionAnswerDescription;
    }

    public String getQuestionAnswerAltDescription() {
        return QuestionAnswerAltDescription;
    }

    public void setQuestionAnswerAltDescription(String QuestionAnswerAltDescription) {
        this.QuestionAnswerAltDescription = QuestionAnswerAltDescription;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
