package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table Reasons.
 */
public class Reasons implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String ReasonCode;
    private String ReasonType;
    private String ReasonName;
    private String ReasonAltName;
    private Integer ReasonDisplaySequence;
    private String ReasonAffectStock;
    private String WarehouseCode;
    private String AccountNumber;
    /** Not-null value. */
    private java.util.Date StampDate;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

	private static final long serialVersionUID = 1L;

    public Reasons() {
    }

    public Reasons(Long id) {
        this.id = id;
    }

    public Reasons(Long id, String ReasonCode, String ReasonType, String ReasonName, String ReasonAltName, Integer ReasonDisplaySequence, String ReasonAffectStock, String WarehouseCode, String AccountNumber, java.util.Date StampDate) {
        this.id = id;
        this.ReasonCode = ReasonCode;
        this.ReasonType = ReasonType;
        this.ReasonName = ReasonName;
        this.ReasonAltName = ReasonAltName;
        this.ReasonDisplaySequence = ReasonDisplaySequence;
        this.ReasonAffectStock = ReasonAffectStock;
        this.WarehouseCode = WarehouseCode;
        this.AccountNumber = AccountNumber;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getReasonCode() {
        return ReasonCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setReasonCode(String ReasonCode) {
        this.ReasonCode = ReasonCode;
    }

    public String getReasonType() {
        return ReasonType;
    }

    public void setReasonType(String ReasonType) {
        this.ReasonType = ReasonType;
    }

    public String getReasonName() {
        return ReasonName;
    }

    public void setReasonName(String ReasonName) {
        this.ReasonName = ReasonName;
    }

    public String getReasonAltName() {
        return ReasonAltName;
    }

    public void setReasonAltName(String ReasonAltName) {
        this.ReasonAltName = ReasonAltName;
    }

    public Integer getReasonDisplaySequence() {
        return ReasonDisplaySequence;
    }

    public void setReasonDisplaySequence(Integer ReasonDisplaySequence) {
        this.ReasonDisplaySequence = ReasonDisplaySequence;
    }

    public String getReasonAffectStock() {
        return ReasonAffectStock;
    }

    public void setReasonAffectStock(String ReasonAffectStock) {
        this.ReasonAffectStock = ReasonAffectStock;
    }

    public String getWarehouseCode() {
        return WarehouseCode;
    }

    public void setWarehouseCode(String WarehouseCode) {
        this.WarehouseCode = WarehouseCode;
    }

    public String getAccountNumber() {
        return AccountNumber;
    }

    public void setAccountNumber(String AccountNumber) {
        this.AccountNumber = AccountNumber;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public String toString () {
    	return ReasonName;
    }
    
	@Override
	public boolean equals ( Object object ) {
		// Flag used to indicate if the objects are equal
		boolean isEqual = false;
		// Check if the object is valid and instance of Reasons
		if ( object != null && object instanceof Reasons )
			// Compare objects
			isEqual = ReasonCode.equals ( ( (Reasons) object ).getReasonCode () );
		// Return flag
		return isEqual;
	}
    // KEEP METHODS END

}
