package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ShareOfShelves.
 */
public class ShareOfShelves implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String ClientCode;
    /** Not-null value. */
    private String CompanyCode;
    /** Not-null value. */
    private String DivisionCode;
    /** Not-null value. */
    private String BrandCode;
    private Double ShareOfShelf;
    private Double ShareOfShelfCompetitor;
    private Double Category;
    private Double BDAYearlyMeter;
    private Double BDAYearlyPercentage;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public ShareOfShelves() {
    }

    public ShareOfShelves(Long id) {
        this.id = id;
    }

    public ShareOfShelves(Long id, String ClientCode, String CompanyCode, String DivisionCode, String BrandCode, Double ShareOfShelf, Double ShareOfShelfCompetitor, Double Category, Double BDAYearlyMeter, Double BDAYearlyPercentage, java.util.Date StampDate) {
        this.id = id;
        this.ClientCode = ClientCode;
        this.CompanyCode = CompanyCode;
        this.DivisionCode = DivisionCode;
        this.BrandCode = BrandCode;
        this.ShareOfShelf = ShareOfShelf;
        this.ShareOfShelfCompetitor = ShareOfShelfCompetitor;
        this.Category = Category;
        this.BDAYearlyMeter = BDAYearlyMeter;
        this.BDAYearlyPercentage = BDAYearlyPercentage;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getClientCode() {
        return ClientCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setClientCode(String ClientCode) {
        this.ClientCode = ClientCode;
    }

    /** Not-null value. */
    public String getCompanyCode() {
        return CompanyCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCompanyCode(String CompanyCode) {
        this.CompanyCode = CompanyCode;
    }

    /** Not-null value. */
    public String getDivisionCode() {
        return DivisionCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDivisionCode(String DivisionCode) {
        this.DivisionCode = DivisionCode;
    }

    /** Not-null value. */
    public String getBrandCode() {
        return BrandCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBrandCode(String BrandCode) {
        this.BrandCode = BrandCode;
    }

    public Double getShareOfShelf() {
        return ShareOfShelf;
    }

    public void setShareOfShelf(Double ShareOfShelf) {
        this.ShareOfShelf = ShareOfShelf;
    }

    public Double getShareOfShelfCompetitor() {
        return ShareOfShelfCompetitor;
    }

    public void setShareOfShelfCompetitor(Double ShareOfShelfCompetitor) {
        this.ShareOfShelfCompetitor = ShareOfShelfCompetitor;
    }

    public Double getCategory() {
        return Category;
    }

    public void setCategory(Double Category) {
        this.Category = Category;
    }

    public Double getBDAYearlyMeter() {
        return BDAYearlyMeter;
    }

    public void setBDAYearlyMeter(Double BDAYearlyMeter) {
        this.BDAYearlyMeter = BDAYearlyMeter;
    }

    public Double getBDAYearlyPercentage() {
        return BDAYearlyPercentage;
    }

    public void setBDAYearlyPercentage(Double BDAYearlyPercentage) {
        this.BDAYearlyPercentage = BDAYearlyPercentage;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
