package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SOSCategories.
 */
public class SOSCategories implements java.io.Serializable {

    private Long id;
    private String CategoryCode;
    private String CompanyCode;
    private String CategoryName;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public SOSCategories() {
    }

    public SOSCategories(Long id) {
        this.id = id;
    }

    public SOSCategories(Long id, String CategoryCode, String CompanyCode, String CategoryName, java.util.Date StampDate) {
        this.id = id;
        this.CategoryCode = CategoryCode;
        this.CompanyCode = CompanyCode;
        this.CategoryName = CategoryName;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCategoryCode() {
        return CategoryCode;
    }

    public void setCategoryCode(String CategoryCode) {
        this.CategoryCode = CategoryCode;
    }

    public String getCompanyCode() {
        return CompanyCode;
    }

    public void setCompanyCode(String CompanyCode) {
        this.CompanyCode = CompanyCode;
    }

    public String getCategoryName() {
        return CategoryName;
    }

    public void setCategoryName(String CategoryName) {
        this.CategoryName = CategoryName;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
