package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SOSTargetHeaders.
 */
public class SOSTargetHeaders implements java.io.Serializable {

    private Long id;
    private String TargetCode;
    private String CompanyCode;
    private String TargetName;
    private Integer TargetType;
    private String TargetNotes;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public SOSTargetHeaders() {
    }

    public SOSTargetHeaders(Long id) {
        this.id = id;
    }

    public SOSTargetHeaders(Long id, String TargetCode, String CompanyCode, String TargetName, Integer TargetType, String TargetNotes, java.util.Date StampDate) {
        this.id = id;
        this.TargetCode = TargetCode;
        this.CompanyCode = CompanyCode;
        this.TargetName = TargetName;
        this.TargetType = TargetType;
        this.TargetNotes = TargetNotes;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTargetCode() {
        return TargetCode;
    }

    public void setTargetCode(String TargetCode) {
        this.TargetCode = TargetCode;
    }

    public String getCompanyCode() {
        return CompanyCode;
    }

    public void setCompanyCode(String CompanyCode) {
        this.CompanyCode = CompanyCode;
    }

    public String getTargetName() {
        return TargetName;
    }

    public void setTargetName(String TargetName) {
        this.TargetName = TargetName;
    }

    public Integer getTargetType() {
        return TargetType;
    }

    public void setTargetType(Integer TargetType) {
        this.TargetType = TargetType;
    }

    public String getTargetNotes() {
        return TargetNotes;
    }

    public void setTargetNotes(String TargetNotes) {
        this.TargetNotes = TargetNotes;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
