package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SurveyAssignments.
 */
public class SurveyAssignments implements java.io.Serializable {

    private Long id;
    private long SurveyID;
    /** Not-null value. */
    private String AssignmentCode;
    private int AssignmentType;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public SurveyAssignments() {
    }

    public SurveyAssignments(Long id) {
        this.id = id;
    }

    public SurveyAssignments(Long id, long SurveyID, String AssignmentCode, int AssignmentType, java.util.Date StampDate) {
        this.id = id;
        this.SurveyID = SurveyID;
        this.AssignmentCode = AssignmentCode;
        this.AssignmentType = AssignmentType;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getSurveyID() {
        return SurveyID;
    }

    public void setSurveyID(long SurveyID) {
        this.SurveyID = SurveyID;
    }

    /** Not-null value. */
    public String getAssignmentCode() {
        return AssignmentCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAssignmentCode(String AssignmentCode) {
        this.AssignmentCode = AssignmentCode;
    }

    public int getAssignmentType() {
        return AssignmentType;
    }

    public void setAssignmentType(int AssignmentType) {
        this.AssignmentType = AssignmentType;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
