package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TargetAssignments.
 */
public class TargetAssignments implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String TargetCode;
    /** Not-null value. */
    private String AssignmentCode;
    private int AssignmentType;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public TargetAssignments() {
    }

    public TargetAssignments(Long id) {
        this.id = id;
    }

    public TargetAssignments(Long id, String TargetCode, String AssignmentCode, int AssignmentType, java.util.Date StampDate) {
        this.id = id;
        this.TargetCode = TargetCode;
        this.AssignmentCode = AssignmentCode;
        this.AssignmentType = AssignmentType;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTargetCode() {
        return TargetCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTargetCode(String TargetCode) {
        this.TargetCode = TargetCode;
    }

    /** Not-null value. */
    public String getAssignmentCode() {
        return AssignmentCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAssignmentCode(String AssignmentCode) {
        this.AssignmentCode = AssignmentCode;
    }

    public int getAssignmentType() {
        return AssignmentType;
    }

    public void setAssignmentType(int AssignmentType) {
        this.AssignmentType = AssignmentType;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
