package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TargetHeaders.
 */
public class TargetHeaders implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String TargetCode;
    private String TargetName;
    private String TargetAltName;
    private Integer TargetType;
    private Double TargetValue;
    private String DivisionCode;
    private String CompanyCode;
    private java.util.Date StartDate;
    private java.util.Date EndDate;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public TargetHeaders() {
    }

    public TargetHeaders(Long id) {
        this.id = id;
    }

    public TargetHeaders(Long id, String TargetCode, String TargetName, String TargetAltName, Integer TargetType, Double TargetValue, String DivisionCode, String CompanyCode, java.util.Date StartDate, java.util.Date EndDate, java.util.Date StampDate) {
        this.id = id;
        this.TargetCode = TargetCode;
        this.TargetName = TargetName;
        this.TargetAltName = TargetAltName;
        this.TargetType = TargetType;
        this.TargetValue = TargetValue;
        this.DivisionCode = DivisionCode;
        this.CompanyCode = CompanyCode;
        this.StartDate = StartDate;
        this.EndDate = EndDate;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTargetCode() {
        return TargetCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTargetCode(String TargetCode) {
        this.TargetCode = TargetCode;
    }

    public String getTargetName() {
        return TargetName;
    }

    public void setTargetName(String TargetName) {
        this.TargetName = TargetName;
    }

    public String getTargetAltName() {
        return TargetAltName;
    }

    public void setTargetAltName(String TargetAltName) {
        this.TargetAltName = TargetAltName;
    }

    public Integer getTargetType() {
        return TargetType;
    }

    public void setTargetType(Integer TargetType) {
        this.TargetType = TargetType;
    }

    public Double getTargetValue() {
        return TargetValue;
    }

    public void setTargetValue(Double TargetValue) {
        this.TargetValue = TargetValue;
    }

    public String getDivisionCode() {
        return DivisionCode;
    }

    public void setDivisionCode(String DivisionCode) {
        this.DivisionCode = DivisionCode;
    }

    public String getCompanyCode() {
        return CompanyCode;
    }

    public void setCompanyCode(String CompanyCode) {
        this.CompanyCode = CompanyCode;
    }

    public java.util.Date getStartDate() {
        return StartDate;
    }

    public void setStartDate(java.util.Date StartDate) {
        this.StartDate = StartDate;
    }

    public java.util.Date getEndDate() {
        return EndDate;
    }

    public void setEndDate(java.util.Date EndDate) {
        this.EndDate = EndDate;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
