package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Taxes.
 */
public class Taxes implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String TaxCode;
    private String TaxName;
    private String TaxAltName;
    private Double TaxPercentage;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public Taxes() {
    }

    public Taxes(Long id) {
        this.id = id;
    }

    public Taxes(Long id, String TaxCode, String TaxName, String TaxAltName, Double TaxPercentage, java.util.Date StampDate) {
        this.id = id;
        this.TaxCode = TaxCode;
        this.TaxName = TaxName;
        this.TaxAltName = TaxAltName;
        this.TaxPercentage = TaxPercentage;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTaxCode() {
        return TaxCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTaxCode(String TaxCode) {
        this.TaxCode = TaxCode;
    }

    public String getTaxName() {
        return TaxName;
    }

    public void setTaxName(String TaxName) {
        this.TaxName = TaxName;
    }

    public String getTaxAltName() {
        return TaxAltName;
    }

    public void setTaxAltName(String TaxAltName) {
        this.TaxAltName = TaxAltName;
    }

    public Double getTaxPercentage() {
        return TaxPercentage;
    }

    public void setTaxPercentage(Double TaxPercentage) {
        this.TaxPercentage = TaxPercentage;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
