package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TotalClientDues.
 */
public class TotalClientDues implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String ParentCode;
    /** Not-null value. */
    private String CurrencyCode;
    private int InvoiceType;
    /** Not-null value. */
    private String CompanyCode;
    /** Not-null value. */
    private String CompanyName;
    private double OriginalAmount;
    private double RemainingAmount;
    private double OverdueAmount;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public TotalClientDues() {
    }

    public TotalClientDues(Long id) {
        this.id = id;
    }

    public TotalClientDues(Long id, String ParentCode, String CurrencyCode, int InvoiceType, String CompanyCode, String CompanyName, double OriginalAmount, double RemainingAmount, double OverdueAmount, java.util.Date StampDate) {
        this.id = id;
        this.ParentCode = ParentCode;
        this.CurrencyCode = CurrencyCode;
        this.InvoiceType = InvoiceType;
        this.CompanyCode = CompanyCode;
        this.CompanyName = CompanyName;
        this.OriginalAmount = OriginalAmount;
        this.RemainingAmount = RemainingAmount;
        this.OverdueAmount = OverdueAmount;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getParentCode() {
        return ParentCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setParentCode(String ParentCode) {
        this.ParentCode = ParentCode;
    }

    /** Not-null value. */
    public String getCurrencyCode() {
        return CurrencyCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCurrencyCode(String CurrencyCode) {
        this.CurrencyCode = CurrencyCode;
    }

    public int getInvoiceType() {
        return InvoiceType;
    }

    public void setInvoiceType(int InvoiceType) {
        this.InvoiceType = InvoiceType;
    }

    /** Not-null value. */
    public String getCompanyCode() {
        return CompanyCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCompanyCode(String CompanyCode) {
        this.CompanyCode = CompanyCode;
    }

    /** Not-null value. */
    public String getCompanyName() {
        return CompanyName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCompanyName(String CompanyName) {
        this.CompanyName = CompanyName;
    }

    public double getOriginalAmount() {
        return OriginalAmount;
    }

    public void setOriginalAmount(double OriginalAmount) {
        this.OriginalAmount = OriginalAmount;
    }

    public double getRemainingAmount() {
        return RemainingAmount;
    }

    public void setRemainingAmount(double RemainingAmount) {
        this.RemainingAmount = RemainingAmount;
    }

    public double getOverdueAmount() {
        return OverdueAmount;
    }

    public void setOverdueAmount(double OverdueAmount) {
        this.OverdueAmount = OverdueAmount;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
