package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table UserCycles.
 */
public class UserCycles implements java.io.Serializable {

    private Long id;
    private int CycleID;
    /** Not-null value. */
    private String UserCode;
    /** Not-null value. */
    private String CompanyCode;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public UserCycles() {
    }

    public UserCycles(Long id) {
        this.id = id;
    }

    public UserCycles(Long id, int CycleID, String UserCode, String CompanyCode, java.util.Date StampDate) {
        this.id = id;
        this.CycleID = CycleID;
        this.UserCode = UserCode;
        this.CompanyCode = CompanyCode;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getCycleID() {
        return CycleID;
    }

    public void setCycleID(int CycleID) {
        this.CycleID = CycleID;
    }

    /** Not-null value. */
    public String getUserCode() {
        return UserCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserCode(String UserCode) {
        this.UserCode = UserCode;
    }

    /** Not-null value. */
    public String getCompanyCode() {
        return CompanyCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCompanyCode(String CompanyCode) {
        this.CompanyCode = CompanyCode;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
