package me.SyncWise.Android.Database;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;

import me.SyncWise.Android.Database.VehiclesStock;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table VehiclesStock.
*/
public class VehiclesStockDao extends AbstractDao<VehiclesStock, Long> {

    public static final String TABLENAME = "VehiclesStock";

    /**
     * Properties of entity VehiclesStock.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property VehicleCode = new Property(1, String.class, "VehicleCode", false, "VehicleCode");
        public final static Property ItemCode = new Property(2, String.class, "ItemCode", false, "ItemCode");
        public final static Property GoodQuantity = new Property(3, Double.class, "GoodQuantity", false, "GoodQuantity");
        public final static Property DamageQuantity = new Property(4, Double.class, "DamageQuantity", false, "DamageQuantity");
        public final static Property DivisionCode = new Property(5, String.class, "DivisionCode", false, "DivisionCode");
        public final static Property CompanyCode = new Property(6, String.class, "CompanyCode", false, "CompanyCode");
        public final static Property ItemLots = new Property(7, String.class, "ItemLots", false, "ItemLots");
        public final static Property StampDate = new Property(8, java.util.Date.class, "StampDate", false, "StampDate");
    };


    public VehiclesStockDao(DaoConfig config) {
        super(config);
    }
    
    public VehiclesStockDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'VehiclesStock' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'VehicleCode' TEXT NOT NULL ," + // 1: VehicleCode
                "'ItemCode' TEXT NOT NULL ," + // 2: ItemCode
                "'GoodQuantity' REAL," + // 3: GoodQuantity
                "'DamageQuantity' REAL," + // 4: DamageQuantity
                "'DivisionCode' TEXT NOT NULL ," + // 5: DivisionCode
                "'CompanyCode' TEXT NOT NULL ," + // 6: CompanyCode
                "'ItemLots' TEXT," + // 7: ItemLots
                "'StampDate' INTEGER NOT NULL );"); // 8: StampDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'VehiclesStock'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, VehiclesStock entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getVehicleCode());
        stmt.bindString(3, entity.getItemCode());
 
        Double GoodQuantity = entity.getGoodQuantity();
        if (GoodQuantity != null) {
            stmt.bindDouble(4, GoodQuantity);
        }
 
        Double DamageQuantity = entity.getDamageQuantity();
        if (DamageQuantity != null) {
            stmt.bindDouble(5, DamageQuantity);
        }
        stmt.bindString(6, entity.getDivisionCode());
        stmt.bindString(7, entity.getCompanyCode());
 
        String ItemLots = entity.getItemLots();
        if (ItemLots != null) {
            stmt.bindString(8, ItemLots);
        }
        stmt.bindLong(9, entity.getStampDate().getTime());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public VehiclesStock readEntity(Cursor cursor, int offset) {
        VehiclesStock entity = new VehiclesStock( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // VehicleCode
            cursor.getString(offset + 2), // ItemCode
            cursor.isNull(offset + 3) ? null : cursor.getDouble(offset + 3), // GoodQuantity
            cursor.isNull(offset + 4) ? null : cursor.getDouble(offset + 4), // DamageQuantity
            cursor.getString(offset + 5), // DivisionCode
            cursor.getString(offset + 6), // CompanyCode
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // ItemLots
            new java.util.Date(cursor.getLong(offset + 8)) // StampDate
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, VehiclesStock entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setVehicleCode(cursor.getString(offset + 1));
        entity.setItemCode(cursor.getString(offset + 2));
        entity.setGoodQuantity(cursor.isNull(offset + 3) ? null : cursor.getDouble(offset + 3));
        entity.setDamageQuantity(cursor.isNull(offset + 4) ? null : cursor.getDouble(offset + 4));
        entity.setDivisionCode(cursor.getString(offset + 5));
        entity.setCompanyCode(cursor.getString(offset + 6));
        entity.setItemLots(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setStampDate(new java.util.Date(cursor.getLong(offset + 8)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(VehiclesStock entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(VehiclesStock entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
