package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Vehicles.
 */
public class Vehicles implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String VehicleCode;
    /** Not-null value. */
    private String DivisionCode;
    /** Not-null value. */
    private String CompanyCode;
    private String VehicleName;
    private String VehicleAltName;
    private String PlateNumber;
    private Double LoadLimit;
    private Double LastOdometer;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public Vehicles() {
    }

    public Vehicles(Long id) {
        this.id = id;
    }

    public Vehicles(Long id, String VehicleCode, String DivisionCode, String CompanyCode, String VehicleName, String VehicleAltName, String PlateNumber, Double LoadLimit, Double LastOdometer, java.util.Date StampDate) {
        this.id = id;
        this.VehicleCode = VehicleCode;
        this.DivisionCode = DivisionCode;
        this.CompanyCode = CompanyCode;
        this.VehicleName = VehicleName;
        this.VehicleAltName = VehicleAltName;
        this.PlateNumber = PlateNumber;
        this.LoadLimit = LoadLimit;
        this.LastOdometer = LastOdometer;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getVehicleCode() {
        return VehicleCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVehicleCode(String VehicleCode) {
        this.VehicleCode = VehicleCode;
    }

    /** Not-null value. */
    public String getDivisionCode() {
        return DivisionCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDivisionCode(String DivisionCode) {
        this.DivisionCode = DivisionCode;
    }

    /** Not-null value. */
    public String getCompanyCode() {
        return CompanyCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCompanyCode(String CompanyCode) {
        this.CompanyCode = CompanyCode;
    }

    public String getVehicleName() {
        return VehicleName;
    }

    public void setVehicleName(String VehicleName) {
        this.VehicleName = VehicleName;
    }

    public String getVehicleAltName() {
        return VehicleAltName;
    }

    public void setVehicleAltName(String VehicleAltName) {
        this.VehicleAltName = VehicleAltName;
    }

    public String getPlateNumber() {
        return PlateNumber;
    }

    public void setPlateNumber(String PlateNumber) {
        this.PlateNumber = PlateNumber;
    }

    public Double getLoadLimit() {
        return LoadLimit;
    }

    public void setLoadLimit(Double LoadLimit) {
        this.LoadLimit = LoadLimit;
    }

    public Double getLastOdometer() {
        return LastOdometer;
    }

    public void setLastOdometer(Double LastOdometer) {
        this.LastOdometer = LastOdometer;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
