package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table VisitTypes.
 */
public class VisitTypes implements java.io.Serializable {

    private Long id;
    private long VisitID;
    private Integer VisitTypeID;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public VisitTypes() {
    }

    public VisitTypes(Long id) {
        this.id = id;
    }

    public VisitTypes(Long id, long VisitID, Integer VisitTypeID, java.util.Date StampDate) {
        this.id = id;
        this.VisitID = VisitID;
        this.VisitTypeID = VisitTypeID;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getVisitID() {
        return VisitID;
    }

    public void setVisitID(long VisitID) {
        this.VisitID = VisitID;
    }

    public Integer getVisitTypeID() {
        return VisitTypeID;
    }

    public void setVisitTypeID(Integer VisitTypeID) {
        this.VisitTypeID = VisitTypeID;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
