package me.SyncWise.Android.Database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table VisitHistory.
 */
public class VisitHistory implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String UserCode;
    /** Not-null value. */
    private String ClientCode;
    /** Not-null value. */
    private java.util.Date VisitDate;
    /** Not-null value. */
    private String DivisionCode;
    /** Not-null value. */
    private String CompanyCode;
    private Integer Total;
    private Integer BlankVisit;
    private Integer Objective;
    private Integer SalesOrder;
    private Integer SalesInvoice;
    private Integer SalesReturn;
    private Integer SalesRFR;
    private Integer Collection;
    /** Not-null value. */
    private java.util.Date StampDate;

	private static final long serialVersionUID = 1L;

    public VisitHistory() {
    }

    public VisitHistory(Long id) {
        this.id = id;
    }

    public VisitHistory(Long id, String UserCode, String ClientCode, java.util.Date VisitDate, String DivisionCode, String CompanyCode, Integer Total, Integer BlankVisit, Integer Objective, Integer SalesOrder, Integer SalesInvoice, Integer SalesReturn, Integer SalesRFR, Integer Collection, java.util.Date StampDate) {
        this.id = id;
        this.UserCode = UserCode;
        this.ClientCode = ClientCode;
        this.VisitDate = VisitDate;
        this.DivisionCode = DivisionCode;
        this.CompanyCode = CompanyCode;
        this.Total = Total;
        this.BlankVisit = BlankVisit;
        this.Objective = Objective;
        this.SalesOrder = SalesOrder;
        this.SalesInvoice = SalesInvoice;
        this.SalesReturn = SalesReturn;
        this.SalesRFR = SalesRFR;
        this.Collection = Collection;
        this.StampDate = StampDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUserCode() {
        return UserCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserCode(String UserCode) {
        this.UserCode = UserCode;
    }

    /** Not-null value. */
    public String getClientCode() {
        return ClientCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setClientCode(String ClientCode) {
        this.ClientCode = ClientCode;
    }

    /** Not-null value. */
    public java.util.Date getVisitDate() {
        return VisitDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVisitDate(java.util.Date VisitDate) {
        this.VisitDate = VisitDate;
    }

    /** Not-null value. */
    public String getDivisionCode() {
        return DivisionCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDivisionCode(String DivisionCode) {
        this.DivisionCode = DivisionCode;
    }

    /** Not-null value. */
    public String getCompanyCode() {
        return CompanyCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCompanyCode(String CompanyCode) {
        this.CompanyCode = CompanyCode;
    }

    public Integer getTotal() {
        return Total;
    }

    public void setTotal(Integer Total) {
        this.Total = Total;
    }

    public Integer getBlankVisit() {
        return BlankVisit;
    }

    public void setBlankVisit(Integer BlankVisit) {
        this.BlankVisit = BlankVisit;
    }

    public Integer getObjective() {
        return Objective;
    }

    public void setObjective(Integer Objective) {
        this.Objective = Objective;
    }

    public Integer getSalesOrder() {
        return SalesOrder;
    }

    public void setSalesOrder(Integer SalesOrder) {
        this.SalesOrder = SalesOrder;
    }

    public Integer getSalesInvoice() {
        return SalesInvoice;
    }

    public void setSalesInvoice(Integer SalesInvoice) {
        this.SalesInvoice = SalesInvoice;
    }

    public Integer getSalesReturn() {
        return SalesReturn;
    }

    public void setSalesReturn(Integer SalesReturn) {
        this.SalesReturn = SalesReturn;
    }

    public Integer getSalesRFR() {
        return SalesRFR;
    }

    public void setSalesRFR(Integer SalesRFR) {
        this.SalesRFR = SalesRFR;
    }

    public Integer getCollection() {
        return Collection;
    }

    public void setCollection(Integer Collection) {
        this.Collection = Collection;
    }

    /** Not-null value. */
    public java.util.Date getStampDate() {
        return StampDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStampDate(java.util.Date StampDate) {
        this.StampDate = StampDate;
    }

}
